package com.ryanpatrick.mhrisearmorsetsearcher.util;

import com.ryanpatrick.mhrisearmorsetsearcher.ApplicationSingleton;
import com.ryanpatrick.mhrisearmorsetsearcher.R;
import com.ryanpatrick.mhrisearmorsetsearcher.model.pojos.Armor;
import com.ryanpatrick.mhrisearmorsetsearcher.model.pojos.Decoration;
import com.ryanpatrick.mhrisearmorsetsearcher.model.pojos.Skill;
import com.ryanpatrick.mhrisearmorsetsearcher.model.pojos.Slot;
import com.ryanpatrick.mhrisearmorsetsearcher.util.enums.ArmorType;
import com.ryanpatrick.mhrisearmorsetsearcher.util.enums.Gender;

public class DbConstants {

    public static final Armor[] PREPOPULATE_ARMORS = {
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bazel_head),
            7, Gender.Both, ArmorType.Head, 72, 92, 3, 1,
            -4, -2, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bazel_chest),
                    7, Gender.Both, ArmorType.Chest, 72, 92, 3, 1,
                    -4, -2, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bazel_arms),
                    7, Gender.Both, ArmorType.Arms, 72, 92, 3, 1,
                    -4, -2, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bazel_waist),
                    7, Gender.Both, ArmorType.Waist, 72, 92, 3, 1,
                    -4, -2, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bazel_legs),
                    7, Gender.Both, ArmorType.Legs, 72, 92, 3, 1,
                    -4, -2, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.damascus_head),
                    7, Gender.Both, ArmorType.Head, 68, 88, -1, 2,
                    -3, 1, -1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.damascus_chest),
                    7, Gender.Both, ArmorType.Chest, 68, 88, -1, 2,
                    -3, 1, -1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.damascus_arms),
                    7, Gender.Both, ArmorType.Arms, 68, 88, -1, 2,
                    -3, 1, -1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.damascus_waist),
                    7, Gender.Both, ArmorType.Waist, 68, 88, -1, 2,
                    -3, 1, -1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.damascus_legs),
                    7, Gender.Both, ArmorType.Legs, 68, 88, -1, 2,
                    -3, 1, -1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.flame_seal),
                    7, Gender.Both, ArmorType.Head, 56, 76, 3, 0,
                    0, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.golden_head),
                    7, Gender.Both, ArmorType.Head, 70, 90,2, 1,
                    3, -5, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.golden_head),
                    7, Gender.Both, ArmorType.Head, 70, 90,2, 1,
                    3, -5, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.golden_chest),
                    7, Gender.Both, ArmorType.Chest, 70, 90,2, 1,
                    3, -5, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.golden_arms),
                    7, Gender.Both, ArmorType.Arms, 70, 90,2, 1,
                    3, -5, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.golden_waist),
                    7, Gender.Both, ArmorType.Waist, 70, 90,2, 1,
                    3, -5, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.golden_legs),
                    7, Gender.Both, ArmorType.Legs, 70, 90,2, 1,
                    3, -5, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ibushi_head_1),
                    7, Gender.Both, ArmorType.Head, 66, 86, -1, 0,
                    0, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ibushi_breastplate_1),
                    7, Gender.Both, ArmorType.Chest, 66, 86, -1, 0,
                    0, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ibushi_pauldrons_1),
                    7, Gender.Both, ArmorType.Arms, 66, 86, -1, 0,
                    0, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ibushi_fauld_1),
                    7, Gender.Both, ArmorType.Waist, 66, 86, -1, 0,
                    0, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ibushi_foot_1),
                    7, Gender.Both, ArmorType.Legs, 66, 86, -1, 0,
                    0, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ibushi_head_1),
                    7, Gender.Both, ArmorType.Head, 66, 86, -1, 0,
                    0, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ibushi_breastplate_2),
                    7, Gender.Both, ArmorType.Chest, 66, 86, -1, 0,
                    0, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ibushi_pauldrons_2),
                    7, Gender.Both, ArmorType.Arms, 66, 86, -1, 0,
                    0, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ibushi_fauld_2),
                    7, Gender.Both, ArmorType.Waist, 66, 86, -1, 0,
                    0, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ibushi_foot_2),
                    7, Gender.Both, ArmorType.Legs, 66, 86, -1, 0,
                    0, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kaiser_head),
                    7, Gender.Both, ArmorType.Head, 74, 94, 4, -4,
                    1, -1, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kaiser_chest),
                    7, Gender.Both, ArmorType.Chest, 74, 94, 4, -4,
                    1, -1, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kaiser_arms),
                    7, Gender.Both, ArmorType.Arms, 74, 94, 4, -4,
                    1, -1, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kaiser_waist),
                    7, Gender.Both, ArmorType.Waist, 74, 94, 4, -4,
                    1, -1, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kaiser_legs),
                    7, Gender.Both, ArmorType.Legs, 74, 94, 4, -4,
                    1, -1, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kushala_head),
                    7, Gender.Both, ArmorType.Head, 74, 94, -1, 2,
                    -2, 3, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kushala_chest),
                    7, Gender.Both, ArmorType.Chest, 74, 94, -1, 2,
                    -2, 3, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kushala_arms),
                    7, Gender.Both, ArmorType.Arms, 74, 94, -1, 2,
                    -2, 3, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kushala_waist),
                    7, Gender.Both, ArmorType.Waist, 74, 94, -1, 2,
                    -2, 3, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kushala_legs),
                    7, Gender.Both, ArmorType.Legs, 74, 94, -1, 2,
                    -2, 3, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mizuha_head),
                    7, Gender.Both, ArmorType.Head, 74, 94, -5, 1,
                    0, 3, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mizuha_chest),
                    7, Gender.Both, ArmorType.Chest, 74, 94, -5, 1,
                    0, 3, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mizuha_arms),
                    7, Gender.Both, ArmorType.Arms, 74, 94, -5, 1,
                    0, 3, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mizuha_waist),
                    7, Gender.Both, ArmorType.Waist, 74, 94, -5, 1,
                    0, 3, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mizuha_legs),
                    7, Gender.Both, ArmorType.Legs, 74, 94, -5, 1,
                    0, 3, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narwa_head_1),
                    7, Gender.Both, ArmorType.Head, 76, 96, 2, 1,
                    4, -3, -4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narwa_breastplate_1),
                    7, Gender.Both, ArmorType.Chest, 76, 96, 2, 1,
                    4, -3, -4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narwa_pauldrons_1),
                    7, Gender.Both, ArmorType.Arms, 76, 96, 2, 1,
                    4, -3, -4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narwa_fauld_1),
                    7, Gender.Both, ArmorType.Waist, 76, 96, 2, 1,
                    4, -3, -4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narwa_foot_1),
                    7, Gender.Both, ArmorType.Legs, 76, 96, 2, 1,
                    4, -3, -4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narwa_head_2),
                    7, Gender.Both, ArmorType.Head, 76, 96, 2, 1,
                    4, -3, -4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narwa_breastplate_2),
                    7, Gender.Both, ArmorType.Chest, 76, 96, 2, 1,
                    4, -3, -4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narwa_pauldrons_2),
                    7, Gender.Both, ArmorType.Arms, 76, 96, 2, 1,
                    4, -3, -4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narwa_fauld_2),
                    7, Gender.Both, ArmorType.Waist, 76, 96, 2, 1,
                    4, -3, -4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narwa_foot_2),
                    7, Gender.Both, ArmorType.Legs, 76, 96, 2, 1,
                    4, -3, -4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.valstrax_head),
                    7, Gender.Both, ArmorType.Head, 80, 100, -2, -2,
                    -2, -2, 3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.valstrax_chest),
                    7, Gender.Both, ArmorType.Chest, 80, 100, -2, -2,
                    -2, -2, 3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.valstrax_arms),
                    7, Gender.Both, ArmorType.Arms, 80, 100, -2, -2,
                    -2, -2, 3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.valstrax_waist),
                    7, Gender.Both, ArmorType.Waist, 80, 100, -2, -2,
                    -2, -2, 3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.valstrax_legs),
                    7, Gender.Both, ArmorType.Legs, 80, 100, -2, -2,
                    -2, -2, 3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.aelucanth_head),
                    6, Gender.Male, ArmorType.Head, 62, 82, -2, 0, 
                    3, -2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.aelucanth_chest),
                    6, Gender.Male, ArmorType.Chest, 62, 82, -2, 0,
                    3, -2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.aelucanth_arms),
                    6, Gender.Male, ArmorType.Arms, 62, 82, -2, 0,
                    3, -2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.aelucanth_waist),
                    6, Gender.Male, ArmorType.Waist, 62, 82, -2, 0,
                    3, -2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.aelucanth_legs),
                    6, Gender.Male, ArmorType.Legs, 62, 82, -2, 0,
                    3, -2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rhopessa_head),
                    6, Gender.Male, ArmorType.Head, 62, 82, -2, 0,
                    3, -2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rhopessa_chest),
                    6, Gender.Male, ArmorType.Chest, 62, 82, -2, 0,
                    3, -2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rhopessa_arms),
                    6, Gender.Male, ArmorType.Arms, 62, 82, -2, 0,
                    3, -2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rhopessa_waist),
                    6, Gender.Male, ArmorType.Waist, 62, 82, -2, 0,
                    3, -2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rhopessa_legs),
                    6, Gender.Male, ArmorType.Legs, 62, 82, -2, 0,
                    3, -2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.almudron_head),
                    6, Gender.Both, ArmorType.Head, 64, 84, -4 ,3,
                    3, -2, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.anja_head),
                    6, Gender.Both, ArmorType.Head, 60, 80, 3, -3,
                    -1, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.anja_chest),
                    6, Gender.Both, ArmorType.Chest, 60, 80, 3, -3,
                    -1, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.anja_arms),
                    6, Gender.Both, ArmorType.Arms, 60, 80, 3, -3,
                    -1, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.anja_waist),
                    6, Gender.Both, ArmorType.Waist, 60, 80, 3, -3,
                    -1, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.anja_head),
                    6, Gender.Both, ArmorType.Head, 60, 80, 3, -3,
                    -1, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.brigade_head),
                    6, Gender.Both, ArmorType.Head, 62, 82, 1, 0,
                    2, 0, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.cunning_specs),
                    6, Gender.Both, ArmorType.Head, 60, 80, 2, 2,
                    2, 2, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.diablos_head),
                    6, Gender.Both, ArmorType.Head, 64, 84, 3, -1,
                    -1, -3, -1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.gargwa_mask),
                    6, Gender.Both, ArmorType.Head, 54, 74, -3, -2,
                    -2, 1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.goss_head),
                    6, Gender.Both, ArmorType.Head, 64, 84, -4, 1,
                    -1, 4, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.jelly_head),
                    6, Gender.Both, ArmorType.Head, 62, 82, 1, 3,
                    0, 2, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.might_bow_feather),
                    6, Gender.Both, ArmorType.Head, 56, 76, 0, 0,
                    0, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mizu_head),
                    6, Gender.Both, ArmorType.Head, 60, 80, 0, 2,
                    -3, 1, -1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.narga_head),
                    6, Gender.Both, ArmorType.Head, 60, 80, -2, 1,
                    -3, 1, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rakna_head),
                    6, Gender.Both, ArmorType.Head, 66, 86, 4, -2,
                    -1, -3, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rathalos_head),
                    6, Gender.Both, ArmorType.Head, 62, 82, 3, 1,
                    -2, 1, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sinister_head),
                    6, Gender.Both, ArmorType.Head, 64, 84, 3, -3,
                    -2, 1, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.tigrex_head),
                    6, Gender.Both, ArmorType.Head, 64, 84, 2, 0,
                    -3, 0, -2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.zinogre_head),
                    6, Gender.Both, ArmorType.Head, 62, 82, 0, -1,
                    -4,4, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.barioth_head),
                    5, Gender.Both, ArmorType.Head, 58,78, -3, 0,
                    -1, 3, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.basarios_head),
                    5, Gender.Both, ArmorType.Head, 52, 82, 0, -2,
                    1, 1, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.channeler_head),
                    5, Gender.Female, ArmorType.Head, 52, 82, 3, 0,
                    0, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.utsuhi_h_head),
                    5, Gender.Male, ArmorType.Head, 52, 82, 3, 0,
                    0, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.death_stench_head),
                    5, Gender.Both, ArmorType.Head, 52, 82, 3, 1,
                    1, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.dober_head),
                    5, Gender.Both, ArmorType.Head, 52, 82, -2, 0,
                    0, 0, 4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.jyura_head),
                    5, Gender.Both, ArmorType.Head, 48, 78, -1, 2,
                    -3, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.tobi_head),
                    5, Gender.Both, ArmorType.Head, 58, 78, 0, -3,
                    3, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.makluva_head),
                    5, Gender.Both, ArmorType.Head, 52, 82, 1, 2,
                    -2, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.medium_head),
                    5, Gender.Female, ArmorType.Head, 52, 82, 3, 0,
                    0, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.utsuhi_h_head),
                    5, Gender.Male, ArmorType.Head, 52, 82, 3, 0,
                    0, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.melahoa_head),
                    5, Gender.Both, ArmorType.Head, 52, 82, 0,1,
                    3, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mosgharl_head),
                    5, Gender.Both, ArmorType.Head, 52, 82, -3, 1,
                    0, 3, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.pukei_head),
                    5, Gender.Both, ArmorType.Head, 50, 80, 0, 3,
                    -3, 0, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rathian_head),
                    5, Gender.Both, ArmorType.Head, 52, 82, 3, 0,
                    -2, 0, -3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.remobra_head),
                    5, Gender.Both, ArmorType.Head, 52, 82, 1, 1,
                    1, 1, 3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.studded_head),
                    5, Gender.Both, ArmorType.Head, 52, 82, 0, 2,
                    1, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.skull_head),
                    5, Gender.Both, ArmorType.Head, 50, 80, -3, -3,
                    -3, -3, 4,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.somnacanth_head),
                    5, Gender.Both, ArmorType.Head, 58, 78, -1, 2,
                    -3, 0, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.vaik_head),
                    5, Gender.Both, ArmorType.Head, 52, 82, 0, 3,
                    -2, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.aknosom_head),
                    4, Gender.Both, ArmorType.Head, 38, 76, 3, -3,
                    -1, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.alloy_head),
                    4, Gender.Both, ArmorType.Head, 32, 70, -1, 0,
                    -1, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.arzuros_head),
                    4, Gender.Both, ArmorType.Head, 36, 74, -2, 0,
                    -2, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.baggi_head),
                    4, Gender.Both, ArmorType.Head, 36, 74, -4, -1,
                    -1, 2, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.barroth_head),
                    4, Gender.Both, ArmorType.Head, 50, 80, -3, -1,
                    3, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bishaten_head),
                    4, Gender.Both, ArmorType.Head, 52, 82, -2, 2,
                    2, -4, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bnahabra_head),
                    4, Gender.Both, ArmorType.Head, 34, 72, -2, 0,
                    0, 0, 2,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bone_head),
                    4, Gender.Both, ArmorType.Head, 32, 70, 0, 0,
                    0, -1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bullfango_mask),
                    4, Gender.Both, ArmorType.Head, 36, 74, 0, 4,
                    -2, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.chainmail_head),
                    4, Gender.Both, ArmorType.Head, 32, 70, 0,0 ,
                    1, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.chaos_head),
                    4, Gender.Both, ArmorType.Head, 40, 70, 2, -2,
                    0, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.edel_head),
                    4, Gender.Both, ArmorType.Head, 40, 70, -1, 3,
                    -1, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.hunters_head),
                    4, Gender.Both, ArmorType.Head, 32, 70, 0, 0,
                    0, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ingot_head),
                    4, Gender.Both, ArmorType.Head, 40, 70, -1, -1,
                    1, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.izuchi_head),
                    4, Gender.Both, ArmorType.Head, 36, 74, 2, -1,
                    -2, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.jaggi_mask),
                    4, Gender.Both, ArmorType.Head, 36, 74, 0, 0,
                    0, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kamura_head),
                    4, Gender.Both, ArmorType.Head, 30, 78, 2, 0,
                    0, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.khezu_head),
                    4, Gender.Both, ArmorType.Head, 38, 76, -4, 1,
                    4, 2, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kulu_head),
                    4, Gender.Both, ArmorType.Head, 38, 76, -4, 1,
                    4, 2, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.lagombi_head),
                    4, Gender.Both, ArmorType.Head, 36, 74, -3, 1,
                    0, 3, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ludroth_head),
                    4, Gender.Both, ArmorType.Head, 48, 78, -3, 4,
                    -1, 0, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rhenoplos_head),
                    4, Gender.Both, ArmorType.Head, 42, 72, 2, 0,
                    0, -2, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.skalda_head),
                    4, Gender.Male, ArmorType.Head, 32, 70, 3, -1,
                    -1, -1, 3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.spio_head),
                    4, Gender.Female, ArmorType.Head, 32, 70, 3, -1,
                    -1, -1, 3,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.slagtoth_hood),
                    4, Gender.Both, ArmorType.Head, 42, 72, -2, 2,
                    0, -1, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.tetranadon_head),
                    4, Gender.Both, ArmorType.Head, 40, 70, -1, 4,
                    -2, 1, 0,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.volvidon_head),
                    4, Gender.Both, ArmorType.Head, 50, 80, 2, -3,
                    0, -1, 1,
                    new Skill[]{},
                    new Slot[]{}),
            new Armor(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wroggi_head),
                    4, Gender.Both, ArmorType.Head, 38, 76, 2, -2,
                    1, -4, 0,
                    new Skill[]{},
                    new Slot[]{})
};
    public static final Decoration[] PREPOPULATE_DECORATIONS = {
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mastery),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.masters_touch), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.handicraft),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.handicraft_skill), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.fate),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.good_luck), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.hellfire),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.hellfire_cloak), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.leap),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.jump_master), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.salvo),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rapid_fire_up), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.thrift),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.spare_shot), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.razor),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.razor_sharp), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.spread),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.spread_up), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.pierce),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.pierce_up), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.forceshot),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.normal_rapid_up), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sharp),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.protective_polish), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.blast),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.blast_attack), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sleep),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sleep_attack), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.paralyzer),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.paralysis_attack), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.throttle),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.latent_power), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.crisis),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.resuscitate), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.furor),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.resentment), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.flawless),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.peak_performance), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.challenger),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.agitator), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.tenderizer),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.weakness_exploit), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.critical),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.critical_boost), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.capacity),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ammo_up), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.guardian),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.offensive_guard), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.fungiform),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mushroomancer), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.draw),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.critical_draw), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.precise),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ballistics), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.crit_element),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.critical_element), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.artillery),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.artillery_skill), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sprinter),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.marathon_runner), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.charger),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.focus), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.minds_eye),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.minds_eye_skill), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.potential),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.latent_power), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.trueshot),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.special_ammo_boost), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.magazine),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.load_shells), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.shield),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.guard_up), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ironwall),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.guard), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.refresh),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.stamina_surge), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.enhancer),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.power_prolonger), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mighty),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.maximum_might), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.attack),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.attack_boost), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.expert),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.critical_eye), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.quickswitch),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rapid_morph), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.absorber),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.recoil_down), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.blunt),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bludgeoner), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.quickload),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.reload_speed), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.steadfast),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.stun_res), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.footing),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.tremor_res), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.earplug),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.earplugs_skill), 3),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.counter),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.counterstrike), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bubble),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bubbly_dance), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sniper),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.steadiness), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.gambit),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.punishing_draw), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.jumping),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.evade_extender), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.evasion),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.evade_window), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.brace),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.flinch_free), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sheath),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.quick_sheathe), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wind_res),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.windproof), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ko),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.slugger), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.friendship),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wide_range), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.destroyer),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.partbreaker), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.resistor),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.blight_res), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.gobbler),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.speed_eating), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.protection),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.divine_blessing), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wall_run),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wall_runner), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wirebug),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wirebug_whisperer), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.grinder),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.speed_sharpening), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.enduring),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.item_prolonger), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.recovery),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.recovery_speed), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.medicine),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.recovery_up), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sonorous),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.horn_maestro), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.drain),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.stamina_thief), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.physique),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.constitution), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.venom),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.poison_atk), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.slider),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.affinity_sliding), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bomber),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bombardier), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.blaze),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.fire_atk), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.stream),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.water_atk), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bolt),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.thunder_atk), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.dragon),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.dragon_atk), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.defense),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.def_boost), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.carver),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.carving_pro), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rodeo),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.master_mounter), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.hungerless),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.hunger_res), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.satiated),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.free_meal), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.muck),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.muck_res), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.diversion),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.diversion_skill), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.dive),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.leap_of_faith), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.fortitude),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.fortify), 2),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.geology),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.geologist), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.botany),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.botanist), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.antiblast),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.blast_res), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.pep),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sleep_res), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.antipara),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.para_res), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.antitode),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.poison_res), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.fire_res),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.fire_res_skill), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.water_res),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.water_res_skill), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.thunder_res),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.thunder_res_skill), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ice_res),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ice_res_skill), 1),
            new Decoration(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.dragon_res),
                    ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.dragon_res_skill), 1)};
    public static final Skill[] PREPOPULATE_SKILLS = {
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.masters_touch), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.handicraft_skill), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.good_luck), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.hellfire_cloak), 4),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.jump_master), 1),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rapid_fire_up), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.spare_shot), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.razor_sharp), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.spread_up), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.pierce_up), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.normal_rapid_up), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.protective_polish), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.blast_attack), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sleep_attack), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.paralysis_attack), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.latent_power), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.resuscitate), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.resentment), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.peak_performance), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.agitator), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.weakness_exploit), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.critical_boost), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ammo_up), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.offensive_guard), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.mushroomancer), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.critical_draw), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ballistics), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.critical_element), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.artillery_skill), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.marathon_runner), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.focus), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.minds_eye_skill), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.heroics), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.special_ammo_boost), 2),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.load_shells), 2),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.guard_up), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.guard), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.stamina_surge), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.power_prolonger), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.maximum_might), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.attack_boost), 7),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.critical_eye), 7),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.rapid_morph), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.recoil_down), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bludgeoner), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.reload_speed), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.stun_res), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.tremor_res), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.earplugs_skill), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.counterstrike), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bubbly_dance), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.steadiness), 2),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.punishing_draw), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.evade_extender), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.evade_window), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.flinch_free), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.quick_sheathe), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.windproof), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.slugger), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wide_range), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.partbreaker), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.blight_res), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.speed_eating), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wirebug_whisperer), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.divine_blessing), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wall_runner), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.speed_sharpening), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.item_prolonger), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.recovery_speed), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.recovery_up), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.horn_maestro), 1),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.stamina_thief), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.constitution), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.poison_atk), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.affinity_sliding), 1),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bombardier), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.fire_atk), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.water_atk), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.thunder_atk), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ice_atk), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.dragon_atk), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.def_boost), 7),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.carving_pro), 1),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.master_mounter), 1),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.hunger_res), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.free_meal), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.muck_res), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.diversion_skill), 1),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.leap_of_faith), 1),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.fortify), 1),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.geologist), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.botanist), 4),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.blast_res), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.sleep_res), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.para_res), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.poison_res), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.fire_res_skill), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.water_res_skill), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.thunder_res_skill), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.ice_res_skill), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.dragon_res_skill), 3),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.bow_charge_plus), 1),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.capture_master), 1),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.chameleos_blessing), 4),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.kushala_blessing), 4),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.teostra_blessing), 4),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.dragonheart), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.wind_alignment), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.thunder_alignment), 5),
            new Skill(ApplicationSingleton.getInstance().getContext().getResources().getString(R.string.stormsoul), 5)};
}
